### ISSUE TITLE
Can't create new project

### ISSUE THREAD

**Issue by CurtisGreene-Morgan** [projectpokemon/PPRE#12]
Creating a new Platinum project using PPRE on Linux Mint 18.2 doesn't work. The terminal output complains about not being able to find a config.json file.

**Comment by CurtisGreene-Morgan** [comment]
Also, saving and loading a project doesn't seem to be functioning. I can save, and that leaves a file behind, but the load dialog doesn't show it. It wants a file of type "PPRE Project," but I have no idea what that extension is supposed to be.

The only options PPRE gives are a few project-related options and an Edit Pokemon option, which does nothing except send an error message to the terminal (below).

Attached is a screenshot of the PPRE window, running in VirtualBox as my current Linux version is too new to have a PyQt4 package available. PIP doesn't have it either.

Error message:

`Traceback (most recent call last):
  File "/home/oldsoft/Documents/hg repos/PPRE/ppre/ui/home.py", line 282, in edit_pokemon
    PokemonUserInterface(self.ui.new(), self.session).show()
  File "/home/oldsoft/Documents/hg repos/PPRE/ppre/ui/editpokemon.py", line 11, in __init__
    self.data = Pokemon(session.game)
  File "/home/oldsoft/Documents/hg repos/PPRE/generic/editable.py", line 445, in __init__
    self.define(*args, **kwargs)
  File "/home/oldsoft/Documents/hg repos/PPRE/pokemon/pokemon_container.py", line 19, in define
    self.names = game.text(game.locale_text_id('pokemon_names'))
  File "/home/oldsoft/Documents/hg repos/PPRE/pokemon/game.py", line 317, in locale_text_id
    return self.text_contents[REGION_CODES[self.region_code]][key]
KeyError: 'pokemon_names'`



![Screenshot from 2021-11-01 22-43-49](https://user-images.githubusercontent.com/88403304/139779238-ab70666c-1d74-4823-bc13-28d7d696e6f3.png)
